### ISSUE TITLE
Disable "System Integrity Protection (rootless)"?

### ISSUE THREAD

**Issue by NoLooseEnds** [mroi/mount-diskimage#1]
Hi, contemplating using this method to mount a TimeMachine sparsebundle on a SMB fileserver, but can't seem to copy "mount_diskimage.m" to /sbin – and it looks like it is because "System Integrity Protection (rootless)". 

Do you have to disable "System Integrity Protection (rootless)", or do you have a workaround?

**Comment by mroi** [comment]
Indeed, the /sbin folder is protected by SIP. I always boot into the recovery system to copy mount_diskimage to /sbin. Then everything works fine. No need to completely disable SIP. This step has to be repeated for every major OS upgrade (like Sierra to High Sierra), though. But to me this is acceptable.

Note that you should not copy mount_diskimage.m to /sbin, but you should of course compile it to an executable first.

**Comment by NoLooseEnds** [comment]
Great, thanks for the reply. 

Was hoping not having to do all that, I'm trying to get it into a script for new clients. I think I've ended up with just mounting the diskimage with crontab on boot, but I'll probably go this route if that does not work out as expected.

Thanks again.

**Comment by mroi** [comment]
I guess mounting at boot should work. Let me know if you figure out a clever solution. I don’t like the manual copying either, but so far I stick with it.
